require 'config.options'
require 'config.keymaps'
require 'config.plugins'
require 'config.telescope'
require 'config.treesitter'
require 'config.comment'
require 'config.nvim-tree'
require 'config.toggleterm'
