require("user.keymaps")
require("user.options")
require("user.autocmds")
require("user.lazy-init")
require("user.plugins")
--require("config.cmp")
--require("config.lsp")
--require("config.telescope")
--require("config.treesitter")
--require("config.autopairs")
-- require 'config.comment'
--require("config.nvim-tree")
--require("config.lualine")
--require("config.toggleterm")
--require("config.alpha")
--require("config.dap")
--require("config.indent-line")
--require("config.conform")
